// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Conversation {
    "ID": number;
    "Title": string;
    "Model": string;
    "CreatedAt": string;
}

export interface Message {
    "ID": number;
    "Role": string;
    "Content": string;
}

/**
 * Note is one atomic captured note. Title/Content are AI-formatted at capture;
 * Tags are AI-extracted. The semantic vector lives in note_vectors and the
 * searchable text in the notes_fts virtual table (kept in sync by CreateNote).
 */
export interface Note {
    "ID": number;
    "Title": string;
    "Content": string;
    "Tags": string[] | null;
    "CreatedAt": string;
}
