// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Conversation {
    "ID": number;
    "Title": string;
    "Model": string;
    "CreatedAt": string;

    /** Creates a new Conversation instance. */
    constructor($$source: Partial<Conversation> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     */
    static createFrom($$source: any = {}): Conversation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation($$parsedSource as Partial<Conversation>);
    }
}

export class Message {
    "ID": number;
    "Role": string;
    "Content": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}
