// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Conversation {
    /**
     * Creates a new Conversation instance.
     * @param {Partial<Conversation>} [$$source = {}] - The source object to create the Conversation.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Model"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conversation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation(/** @type {Partial<Conversation>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}
