// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Conversation {
    "ID": number;
    "Title": string;
    "Model": string;
    "CreatedAt": string;
}

export interface Message {
    "ID": number;
    "Role": string;
    "Content": string;
}
