// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "theme": string;
    "language": string;
    "open_key": string;
    "open_interval_ms": number;
    "close_key": string;
    "close_interval_ms": number;
    "model": string;
    "api_key": string;
    "system_prompt": string;

    /**
     * Opacity is the background opacity of the palette shell, 0–100 (percent).
     * Higher is more opaque; the remainder lets the acrylic backdrop show through.
     */
    "opacity": number;

    /**
     * NotesLineLimit é o teto de linhas padrão de uma nota antes de o sistema
     * oferecer resumo/divisão. NotesIntegrationMode escolhe como uma anotação
     * entra na nota: "append" (cola a linha) ou "rewrite" (a IA reorganiza tudo).
     */
    "notes_line_limit": number;
    "notes_integration_mode": string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("open_key" in $$source)) {
            this["open_key"] = "";
        }
        if (!("open_interval_ms" in $$source)) {
            this["open_interval_ms"] = 0;
        }
        if (!("close_key" in $$source)) {
            this["close_key"] = "";
        }
        if (!("close_interval_ms" in $$source)) {
            this["close_interval_ms"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("system_prompt" in $$source)) {
            this["system_prompt"] = "";
        }
        if (!("opacity" in $$source)) {
            this["opacity"] = 0;
        }
        if (!("notes_line_limit" in $$source)) {
            this["notes_line_limit"] = 0;
        }
        if (!("notes_integration_mode" in $$source)) {
            this["notes_integration_mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
