// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "theme": string;
    "language": string;
    "open_key": string;
    "open_interval_ms": number;
    "close_key": string;
    "close_interval_ms": number;
    "model": string;
    "api_key": string;
    "system_prompt": string;
}
