// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "theme": string;
    "language": string;
    "open_key": string;
    "open_interval_ms": number;
    "open_press_count": number;
    "close_key": string;
    "close_interval_ms": number;
    "close_press_count": number;
    "model": string;
    "api_key": string;
    "system_prompt": string;

    /**
     * Opacity is the background opacity of the palette shell, 0–100 (percent).
     * Higher is more opaque; the remainder lets the acrylic backdrop show through.
     */
    "opacity": number;

    /**
     * NoteCharLimit is the global default size ceiling for a single note, in
     * characters (runes). When a capture append would push a note past it, the
     * user is asked how to handle the overflow. A per-note override lives in the
     * notes table (0 there = inherit this default).
     */
    "note_char_limit": number;
}
