// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("open_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["open_key"] = "";
        }
        if (!("open_interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["open_interval_ms"] = 0;
        }
        if (!("close_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["close_key"] = "";
        }
        if (!("close_interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["close_interval_ms"] = 0;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("system_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }
        if (!("opacity" in $$source)) {
            /**
             * Opacity is the background opacity of the palette shell, 0–100 (percent).
             * Higher is more opaque; the remainder lets the acrylic backdrop show through.
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}
