// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertsService creates reminders (AI-parsed) and fires them on a polling loop.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel soft-cancels an alert (status=cancelled), stopping any recurrence.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(id) {
    return $Call.ByID(1343749215, id);
}

/**
 * Create turns a natural-language reminder into a stored alert (1 AI call).
 * @param {string} text
 * @returns {$CancellablePromise<$models.CreateAlertResult>}
 */
export function Create(text) {
    return $Call.ByID(2959703249, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateForNote creates an alert linked to a note: the AI parses only the timing
 * and the message defaults to the note's title.
 * @param {number} noteID
 * @param {string} whenText
 * @returns {$CancellablePromise<$models.CreateAlertResult>}
 */
export function CreateForNote(noteID, whenText) {
    return $Call.ByID(3059866688, noteID, whenText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Done marks an alert done. For a one-shot it's the natural close (idempotent if
 * the scheduler already fired it). For a recurring alert it only dismisses the
 * current occurrence — the scheduler has already rescheduled the next fire_at,
 * so the series continues; cancel the recurrence via Cancel/DeleteAlert instead.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Done(id) {
    return $Call.ByID(4236761741, id);
}

/**
 * List returns alerts the manager shows: pending and done, fire_at ascending.
 * @returns {$CancellablePromise<db$0.Alert[]>}
 */
export function List() {
    return $Call.ByID(3802077101).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RegisterCategory registers the toast action buttons. Called once at boot.
 * @returns {$CancellablePromise<void>}
 */
export function RegisterCategory() {
    return $Call.ByID(3793523940);
}

/**
 * Run drives the polling loop: an immediate tick on boot (catches alerts that
 * came due while the app was closed), then every pollInterval until ctx is done.
 * @returns {$CancellablePromise<void>}
 */
export function Run() {
    return $Call.ByID(1334718574);
}

/**
 * Snooze pushes an alert's fire_at forward by `minutes` and keeps it pending.
 * @param {number} id
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function Snooze(id, minutes) {
    return $Call.ByID(2765897483, id, minutes);
}

// Private type creation functions
const $$createType0 = $models.CreateAlertResult.createFrom;
const $$createType1 = db$0.Alert.createFrom;
const $$createType2 = $Create.Array($$createType1);
