// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertsService creates reminders (AI-parsed) and fires them on a polling loop.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel soft-cancels an alert (status=cancelled), stopping any recurrence.
 */
export function Cancel(id: number): $CancellablePromise<void> {
    return $Call.ByID(1343749215, id);
}

/**
 * Create turns a natural-language reminder into a stored alert (1 AI call).
 */
export function Create(text: string): $CancellablePromise<$models.CreateAlertResult> {
    return $Call.ByID(2959703249, text);
}

/**
 * CreateForNote creates an alert linked to a note: the AI parses only the timing
 * and the message defaults to the note's title.
 */
export function CreateForNote(noteID: number, whenText: string): $CancellablePromise<$models.CreateAlertResult> {
    return $Call.ByID(3059866688, noteID, whenText);
}

/**
 * CreateProposed grava um alerta a partir de campos já parseados (sem chamar a
 * IA). Usado quando o chat (tool call) ou um /note já produziu o horário.
 */
export function CreateProposed(message: string, fireAtISO: string, recurrence: string, noteID: number | null): $CancellablePromise<$models.CreateAlertResult> {
    return $Call.ByID(693182783, message, fireAtISO, recurrence, noteID);
}

/**
 * Done marks an alert done. For a one-shot it's the natural close (idempotent if
 * the scheduler already fired it). For a recurring alert it only dismisses the
 * current occurrence — the scheduler has already rescheduled the next fire_at,
 * so the series continues; cancel the recurrence via Cancel/DeleteAlert instead.
 */
export function Done(id: number): $CancellablePromise<void> {
    return $Call.ByID(4236761741, id);
}

/**
 * GetAlertNoteID returns the note_id of an alert, or nil if unlinked.
 */
export function GetAlertNoteID(id: number): $CancellablePromise<number | null> {
    return $Call.ByID(2510878826, id);
}

/**
 * List returns alerts the manager shows: pending and done, fire_at ascending.
 */
export function List(): $CancellablePromise<db$0.Alert[] | null> {
    return $Call.ByID(3802077101);
}

/**
 * RegisterCategory registers the toast action buttons. Called once at boot.
 */
export function RegisterCategory(): $CancellablePromise<void> {
    return $Call.ByID(3793523940);
}

/**
 * Run drives the polling loop: an immediate tick on boot (catches alerts that
 * came due while the app was closed), then every pollInterval until ctx is done.
 */
export function Run(): $CancellablePromise<void> {
    return $Call.ByID(1334718574);
}

/**
 * Snooze pushes an alert's fire_at forward by `minutes` and keeps it pending.
 */
export function Snooze(id: number, minutes: number): $CancellablePromise<void> {
    return $Call.ByID(2765897483, id, minutes);
}
