// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertSchedulerService arma/cancela toasts agendados do Windows espelhando os
 * alertas do servidor. O diff (desejado vs armado) é testável; o I/O nativo fica
 * atrás de winnotify.Notifier. Os erros do Notifier são repassados ao chamador;
 * cabe a ele decidir se aborta ou continua — agendar é best-effort e não deve
 * bloquear o fluxo de alertas.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArmOne arma a próxima ocorrência de um alerta (no-op se passado/não-ativo).
 */
export function ArmOne(a: $models.ScheduledAlert): $CancellablePromise<void> {
    return $Call.ByID(801625851, a);
}

/**
 * CancelOne remove qualquer ocorrência agendada do alerta.
 */
export function CancelOne(alertID: number): $CancellablePromise<void> {
    return $Call.ByID(531721149, alertID);
}

/**
 * Reconcile alinha o conjunto agendado do SO com a lista de alertas: cancela o
 * que sumiu ou mudou de horário e arma o que falta. Uma ocorrência por alerta.
 */
export function Reconcile(alerts: $models.ScheduledAlert[] | null): $CancellablePromise<void> {
    return $Call.ByID(856968771, alerts);
}
