// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3788130330);
}

export function NewConversation(): $CancellablePromise<void> {
    return $Call.ByID(4263965845);
}

export function Send(text: string): $CancellablePromise<void> {
    return $Call.ByID(3689122830, text);
}
