// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function Current() {
    return $Call.ByID(1329622729).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function Get() {
    return $Call.ByID(3478997624).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Models() {
    return $Call.ByID(252474270).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnSave(fn) {
    return $Call.ByID(3848374488, fn);
}

/**
 * @param {config$0.Config} c
 * @returns {$CancellablePromise<void>}
 */
export function Save(c) {
    return $Call.ByID(1493879465, c);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
