// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2218961615, id);
}

/**
 * @returns {$CancellablePromise<db$0.Conversation[]>}
 */
export function List() {
    return $Call.ByID(1213690252).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<db$0.Message[]>}
 */
export function Messages(id) {
    return $Call.ByID(1792130160, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = db$0.Conversation.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.Message.createFrom;
const $$createType3 = $Create.Array($$createType2);
