// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2218961615, id);
}

export function List(): $CancellablePromise<db$0.Conversation[] | null> {
    return $Call.ByID(1213690252);
}

export function Messages(id: number): $CancellablePromise<db$0.Message[] | null> {
    return $Call.ByID(1792130160, id);
}
