// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScheduledAlert é a forma mínima que o frontend envia ao serviço (vinda de
 * AlertsService.list()/create*). FireAt é RFC3339.
 */
export interface ScheduledAlert {
    "id": number;
    "message": string;
    "fireAt": string;
    "status": string;
}
