// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RouteResult é o que o frontend recebe após um /note. Status:
 *   - "created"    nova nota criada
 *   - "appended"   item anexado a uma nota existente
 *   - "full"       a nota alvo estouraria o limite — pede escolha ao usuário
 *   - "no_api_key" falta a chave da API
 *   - "error"      falha (mensagem em Message)
 */
export interface RouteResult {
    "status": string;
    "noteTitle": string;
    "noteId": number;
    "message": string;
    "tokens": number;
    "cost": number;
}
