// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AskResult is /find plus an AI summary of the top notes.
 */
export class AskResult {
    /**
     * Creates a new AskResult instance.
     * @param {Partial<AskResult>} [$$source = {}] - The source object to create the AskResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {SearchResult[]}
             */
            this["sources"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tokens"] = 0;
        }
        if (!("cost" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AskResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AskResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField2_0($$parsedSource["sources"]);
        }
        return new AskResult(/** @type {Partial<AskResult>} */($$parsedSource));
    }
}

/**
 * CaptureResult is what the frontend gets after a /note.
 * 
 * 	"created"    note stored
 * 	"no_api_key" the API key is missing
 * 	"error"      failure (see Message)
 */
export class CaptureResult {
    /**
     * Creates a new CaptureResult instance.
     * @param {Partial<CaptureResult>} [$$source = {}] - The source object to create the CaptureResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("noteId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["noteId"] = 0;
        }
        if (!("noteTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["noteTitle"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tokens"] = 0;
        }
        if (!("cost" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new CaptureResult(/** @type {Partial<CaptureResult>} */($$parsedSource));
    }
}

/**
 * CreateAlertResult is what the frontend gets after /alerta or "create from note".
 * 
 * 	"created"     alert stored
 * 	"no_api_key"  the API key is missing
 * 	"unparseable" the AI couldn't produce valid JSON / a valid time
 * 	"past"        a one-shot time already in the past
 * 	"error"       failure (e.g. DB)
 */
export class CreateAlertResult {
    /**
     * Creates a new CreateAlertResult instance.
     * @param {Partial<CreateAlertResult>} [$$source = {}] - The source object to create the CreateAlertResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("alertId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alertId"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("fireAtLocal" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fireAtLocal"] = "";
        }
        if (!("recurrence" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["recurrence"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateAlertResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateAlertResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateAlertResult(/** @type {Partial<CreateAlertResult>} */($$parsedSource));
    }
}

/**
 * GraphData is the full graph returned to the frontend.
 */
export class GraphData {
    /**
     * Creates a new GraphData instance.
     * @param {Partial<GraphData>} [$$source = {}] - The source object to create the GraphData.
     */
    constructor($$source = {}) {
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {GraphNode[]}
             */
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            /**
             * @member
             * @type {GraphEdge[]}
             */
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new GraphData(/** @type {Partial<GraphData>} */($$parsedSource));
    }
}

/**
 * GraphEdge is one directed link between notes.
 */
export class GraphEdge {
    /**
     * Creates a new GraphEdge instance.
     * @param {Partial<GraphEdge>} [$$source = {}] - The source object to create the GraphEdge.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source"] = 0;
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphEdge}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge(/** @type {Partial<GraphEdge>} */($$parsedSource));
    }
}

/**
 * GraphNode is one note in the graph.
 */
export class GraphNode {
    /**
     * Creates a new GraphNode instance.
     * @param {Partial<GraphNode>} [$$source = {}] - The source object to create the GraphNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphNode}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new GraphNode(/** @type {Partial<GraphNode>} */($$parsedSource));
    }
}

/**
 * SearchResult is one ranked note for /find and /ask. Content is included so the
 * detail pane can render it without another round-trip.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("noteId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["noteId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = GraphNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GraphEdge.createFrom;
const $$createType6 = $Create.Array($$createType5);
