// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertProposal é um lembrete que o modelo de captura detectou dentro da nota.
 * FireAt é ISO 8601 com offset (como o modelo retornou); Recurrence é JSON
 * marshalado ou "". Presente só quando a nota tem horário/data concretos.
 */
export interface AlertProposal {
    "message": string;
    "fireAt": string;
    "recurrence": string;
}

/**
 * AskResult is /find plus an AI summary of the top notes.
 */
export interface AskResult {
    "status": string;
    "summary": string;
    "sources": SearchResult[] | null;
    "message": string;
    "tokens": number;
    "cost": number;
}

/**
 * CaptureResult is what the frontend gets after a /note.
 * 
 * 	"created"    note stored
 * 	"no_api_key" the API key is missing
 * 	"error"      failure (see Message)
 */
export interface CaptureResult {
    "status": string;
    "noteId": number;
    "noteTitle": string;
    "tags": string[] | null;
    "message": string;
    "tokens": number;
    "cost": number;
    "alert": AlertProposal | null;
}

/**
 * CreateAlertResult is what the frontend gets after /alerta or "create from note".
 * 
 * 	"created"     alert stored
 * 	"no_api_key"  the API key is missing
 * 	"unparseable" the AI couldn't produce valid JSON / a valid time
 * 	"past"        a one-shot time already in the past
 * 	"error"       failure (e.g. DB)
 */
export interface CreateAlertResult {
    "status": string;
    "alertId": number;
    "message": string;
    "fireAtLocal": string;
    "recurrence": string;
}

/**
 * GraphData is the full graph returned to the frontend.
 */
export interface GraphData {
    "nodes": GraphNode[] | null;
    "edges": GraphEdge[] | null;
}

/**
 * GraphEdge is one directed link between notes.
 */
export interface GraphEdge {
    "source": number;
    "target": number;
}

/**
 * GraphNode is one note in the graph.
 */
export interface GraphNode {
    "id": number;
    "title": string;
    "tags": string[] | null;
}

/**
 * SearchResult is one ranked note for /find and /ask. Content is included so the
 * detail pane can render it without another round-trip.
 */
export interface SearchResult {
    "noteId": number;
    "title": string;
    "snippet": string;
    "content": string;
    "tags": string[] | null;
    "score": number;
}
