// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ask searches, then asks the AI to summarize the top notes in answer to the
 * query. Returns the summary plus the source notes it drew from.
 * @param {string} query
 * @returns {$CancellablePromise<$models.AskResult>}
 */
export function Ask(query) {
    return $Call.ByID(3800370906, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Capture formats a quick note with the AI (title + Markdown body + tags),
 * stores it as one atomic note, and indexes it for full-text and (if the model
 * is loaded) semantic search.
 * @param {string} text
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function Capture(text) {
    return $Call.ByID(3530421209, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Delete removes a note and all of its derived rows (tags, vector, FTS).
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2723240770, id);
}

/**
 * Find runs hybrid search (full-text + semantic, fused via RRF). No AI, no cost.
 * @param {string} query
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function Find(query) {
    return $Call.ByID(2852907074, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGraphData returns every note (as a node) and edges between notes that share
 * at least one tag. For each tag, all pairs of notes with that tag are linked.
 * @returns {$CancellablePromise<$models.GraphData>}
 */
export function GetGraphData() {
    return $Call.ByID(2334354237).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * List returns every note, newest first (used by the notes browser).
 * @returns {$CancellablePromise<db$0.Note[]>}
 */
export function List() {
    return $Call.ByID(3779446313).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * Update replaces a note's title, content and tags exactly as the user typed
 * them — no AI, no cost. The text is re-embedded locally (free) when the model
 * is loaded so semantic search stays in sync; otherwise the note keeps no vector
 * and degrades to full-text. Tags are normalized but uncapped (manual edit).
 * Returns the updated note for the UI to re-render.
 * @param {number} id
 * @param {string} title
 * @param {string} content
 * @param {string[]} tags
 * @returns {$CancellablePromise<db$0.Note>}
 */
export function Update(id, title, content, tags) {
    return $Call.ByID(579506140, id, title, content, tags).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AskResult.createFrom;
const $$createType1 = $models.CaptureResult.createFrom;
const $$createType2 = $models.SearchResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.GraphData.createFrom;
const $$createType5 = db$0.Note.createFrom;
const $$createType6 = $Create.Array($$createType5);
