// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendTo appends already-formatted content to the end of an existing note,
 * re-embedding the combined text and keeping FTS/vector/tags in sync (tags are
 * the union of old and new). Used when the capture router decides to attach and
 * the user confirms. No AI call.
 */
export function AppendTo(targetID: number, content: string, tags: string[] | null): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(873500712, targetID, content, tags);
}

/**
 * Ask searches, then asks the AI to summarize the top notes in answer to the
 * query. Returns the summary plus the source notes it drew from.
 */
export function Ask(query: string): $CancellablePromise<$models.AskResult> {
    return $Call.ByID(3800370906, query);
}

/**
 * Capture formats a quick note with the AI (title + Markdown body + tags),
 * stores it as one atomic note, and indexes it for full-text and (if the model
 * is loaded) semantic search.
 */
export function Capture(text: string): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(3530421209, text);
}

/**
 * CreateFromProposal stores a note directly from already-parsed fields (no AI
 * call). Used when the chat model proposes a note via tool call.
 */
export function CreateFromProposal(title: string, content: string, tags: string[] | null): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(704494767, title, content, tags);
}

/**
 * Delete removes a note and all of its derived rows (tags, vector, FTS).
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2723240770, id);
}

/**
 * Find runs hybrid search (full-text + semantic, fused via RRF). No AI, no cost.
 */
export function Find(query: string): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(2852907074, query);
}

/**
 * GetGraphData returns every note (as a node) and edges between notes that share
 * at least one tag. For each tag, all pairs of notes with that tag are linked.
 */
export function GetGraphData(): $CancellablePromise<$models.GraphData> {
    return $Call.ByID(2334354237);
}

/**
 * List returns every note, newest first (used by the notes browser).
 */
export function List(): $CancellablePromise<db$0.Note[] | null> {
    return $Call.ByID(3779446313);
}

/**
 * ResolveOverflow applies the user's chosen strategy for content that overflowed
 * a note (see AppendTo). mode is one of:
 * 
 * 	"summarize" — merge old+new, ask the AI to condense the combined note to fit
 * 	"part2"     — leave the note as-is, put the new content in a linked sibling
 * 	"split"     — merge, then ask the AI to divide everything into themed notes
 */
export function ResolveOverflow(targetID: number, content: string, tags: string[] | null, mode: string): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(1700925705, targetID, content, tags, mode);
}

/**
 * SetCharLimit sets a per-note size override in characters; 0 clears it so the
 * note falls back to the global default (config.NoteCharLimit). Negative values
 * are clamped to 0.
 */
export function SetCharLimit(id: number, limit: number): $CancellablePromise<void> {
    return $Call.ByID(2052939502, id, limit);
}

/**
 * Summarize asks the AI to condense one note into a shorter Markdown summary. It
 * does not modify the note; the frontend applies the result via Update (so the
 * change is undoable) when the user confirms.
 */
export function Summarize(id: number): $CancellablePromise<$models.SummarizeResult> {
    return $Call.ByID(4276641010, id);
}

/**
 * Tidy asks the AI to reorganize one note — group related points, add structure
 * (headings/lists/tasks), fix the Markdown, order it logically — without removing
 * or inventing information. It does not modify the note; the frontend applies the
 * result via Update (so the change is undoable) when the user confirms.
 */
export function Tidy(id: number): $CancellablePromise<$models.TidyResult> {
    return $Call.ByID(117830173, id);
}

/**
 * Update replaces a note's title, content and tags exactly as the user typed
 * them — no AI, no cost. The text is re-embedded locally (free) when the model
 * is loaded so semantic search stays in sync; otherwise the note keeps no vector
 * and degrades to full-text. Tags are normalized but uncapped (manual edit).
 * Returns the updated note for the UI to re-render.
 */
export function Update(id: number, title: string, content: string, tags: string[] | null): $CancellablePromise<db$0.Note> {
    return $Call.ByID(579506140, id, title, content, tags);
}
