// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ResolveOverflow executa a escolha do usuário quando uma nota estoura o limite.
 * strategy: "summarize" | "part2" | "split".
 */
export function ResolveOverflow(noteID: number, text: string, strategy: string): $CancellablePromise<$models.RouteResult> {
    return $Call.ByID(1700925705, noteID, text, strategy);
}

/**
 * Route decide o destino do texto e aplica a anotação. Ver RouteResult.
 */
export function Route(text: string): $CancellablePromise<$models.RouteResult> {
    return $Call.ByID(1350424422, text);
}
