// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TokenService expõe o cofre de sessão (DPAPI no Windows) ao frontend, para o
 * par de tokens JWT não viver em localStorage no WebView. O frontend serializa
 * {access, refresh} num JSON opaco; o Go só cifra/decifra/persiste a string.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Clear apaga a sessão persistida (logout).
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(3739939762);
}

/**
 * Load devolve o blob salvo, ou "" se não houver sessão persistida.
 */
export function Load(): $CancellablePromise<string> {
    return $Call.ByID(1814240633);
}

/**
 * Save cifra e persiste o blob; string vazia limpa o cofre.
 */
export function Save(data: string): $CancellablePromise<void> {
    return $Call.ByID(3156578328, data);
}
