// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationAction represents an action button for a notification.
 */
export interface NotificationAction {
    "id"?: string;
    "title"?: string;

    /**
     * (macOS-specific)
     */
    "destructive"?: boolean;
}

/**
 * NotificationCategory groups actions for notifications.
 */
export interface NotificationCategory {
    "id"?: string;
    "actions"?: NotificationAction[] | null;
    "hasReplyField"?: boolean;
    "replyPlaceholder"?: string;
    "replyButtonTitle"?: string;
}

/**
 * NotificationOptions contains configuration for a notification
 */
export interface NotificationOptions {
    "id": string;
    "title": string;

    /**
     * (macOS and Linux only)
     */
    "subtitle"?: string;
    "body"?: string;
    "categoryId"?: string;
    "data"?: { [_ in string]?: any } | null;
}

/**
 * NotificationResponse represents the response sent by interacting with a notification.
 */
export interface NotificationResponse {
    "id"?: string;
    "actionIdentifier"?: string;
    "categoryIdentifier"?: string;
    "title"?: string;

    /**
     * (macOS and Linux only)
     */
    "subtitle"?: string;
    "body"?: string;
    "userText"?: string;
    "userInfo"?: { [_ in string]?: any } | null;
}

/**
 * NotificationResult represents the result of a notification response,
 * returning the response or any errors that occurred.
 */
export interface NotificationResult {
    "Response": NotificationResponse;
    "Error": any;
}
