// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationAction represents an action button for a notification.
 */
export interface NotificationAction {
    "id"?: string;
    "title"?: string;

    /**
     * (macOS-specific)
     */
    "destructive"?: boolean;
}

/**
 * NotificationCategory groups actions for notifications.
 */
export interface NotificationCategory {
    "id"?: string;
    "actions"?: NotificationAction[] | null;
    "hasReplyField"?: boolean;
    "replyPlaceholder"?: string;
    "replyButtonTitle"?: string;
}

/**
 * NotificationOptions contains configuration for a notification
 */
export interface NotificationOptions {
    "id": string;
    "title": string;

    /**
     * (macOS and Linux only)
     */
    "subtitle"?: string;
    "body"?: string;
    "categoryId"?: string;
    "data"?: { [_ in string]?: any } | null;
}
